@startuml classDesign
class PlayerInfo{
    //DBのテーブルとして使用
    {field} - int player_id
    {field} - String name
    {field} - String password
    {field} - int count_of_play
    {field} - int count_of_win
    {field} - int count_of_lose
    {field} - int count_of_offline_play
    {field} - int count_of_online_play
}

class Player{
    {field} - int player_id
    {field} - String name
    {field} - Piece[] pieces // 自分が持っている駒
    {field} - int picked_red_pieces_count //相手から奪った赤駒
    {field} - int picked_blue_pieces_count //相手から奪った青駒
    {method} + void pick() // moveによって相手の駒と重なったら奪う
    {method} + void move(Piece piece, Block destination) //どのコマをどのマスに移動させるか
}

class Piece{
    {field} - String owner 
    {field} - String type //red or blue
    {method} + String getOwner()
    {method} + void setOwner()
    {method} + String getType()
}

class Table{
    {field} - Player[] players
    {field} - Block[][] table
    {method} + void play() //ゲームの進行を行うメソッド
    {method} + String judgeGameResult() //ゲームの最終的な勝敗を決定するメソッド
}

class Block{
    {field} - int[] address //xy座標（不変）
    {field} - Piece piece //どの駒が配置されているか/null許可
    {field} + void setPiece(Piece piece)
    {field} + Piece getPiece()
}

Piece "1..8" o-- "1" Player
Block "64" o-- "1" Table
Player "2" o-- "1" Table

@enduml