@startuml ガイスター
start
:ログイン;
:ロビー画面でオフライン/オンラインを選択;
if(オンラインモード) then (true)
    if(ホスト) then (true)
    :ルーム作成;
    else 
    :ルームコード入力;
    :入室;
    endif
endif
:対戦相手決定;
:各プレイヤーが自分のコマを配置する;
:ゲーム開始;

repeat
  :先攻がコマを進める;
  if(相手のコマと重なる) then (true) 
  :相手のコマを取得;
  endif
  :後攻がコマを進める;
  if(相手のコマと重なる) then (true) 
  :相手のコマを取得;
  endif
repeat while (いずれかのプレイヤーの青いオバケが脱出可能 or いずれかのプレイヤーの青いオバケが0個 or いずれかのプレイヤーの赤いオバケが0個)

stop
@enduml